var shortname = 'bodyglove';
var date = new Date();
var year = date.getFullYear();
var month = date.getMonth() + 1;

var FHConfig = {
  toolType: 'SearchInput',
  shortname: 'bodyglove',
  text: {
    fontPrimary: '',
    headerText: 'Ticket Info',
    mainActionButton: 'Book Now',
    globalTextAlign: '',
  },
  colors: {
    headerColor: '',
    headerTextColor: '',
    mainButtonColor: '',
    mainButtonTextColor: '',
  },
  toolDetails: {
    modal: {
      modalType: 'Simple',
      showFullItems: true,
      cards: {
        numberOfCards: null,
        cardDetail: [
          {
            doesItExist: true,
            text: 'See activities and tickets',
            extraText: '',
            itemID: '',
            linkTo: 'https://demo.fareharbor.com/embeds/book/' + shortname + '/items/?full-items=yes',
          },
          {
            doesItExist: true,
            text: 'View online calendar',
            extraText: '',
            itemID: '',
            linkTo: 'https://demo.fareharbor.com/embeds/book/' + shortname + '/items/calendar/' + year + '/' + month + '/',
          },
          {
            doesItExist: true,
            text: 'Tickets by phone',
            extraText: '555-555-5555',
            itemID: '',
            linkTo: '',
          },
          {
            doesItExist: false,
            text: '',
            extraText: '',
            itemID: '',
            linkTo: '',
          },
        ],
        marginsAndPadding: {
          marginLeft: '',
          marginRight: '',
          marginTop: '',
          marginBottom: '',
          paddingLeft: '',
          paddingRight: '',
          paddingTop: '',
          paddingBottom: '',
        },
      },
    },
    inputFields: {
      inputFieldTypes: {
        leftInputFieldHTMLType: '',
        rightInputFieldHTMLType: '',
        detailsInputFieldHTMLType: '',
        leftInputFieldFunction: '',
        rightInputFieldFunction: '',
      },
      includeDetailsInputField: true,
      inputFieldBackgroundColor: {
        leftInputFieldBackgroundColor: '',
        rightInputFieldBackgroundColor: '',
        detailsInputFieldBackgroundColor: '',
      },
      inputFieldText: {
        leftInputFieldTextAlign: '',
        rightInputFieldTextAlign: '',
        detailsInputFieldTextAlign: '',
        leftInputFieldTextContent: '',
        rightInputFieldTextContent: '',
        detailsInputFieldTextContent: '',
        leftInputFieldTextColor: '',
        rightInputFieldTextColor: '',
        detailsInputFieldTextColor: '',
        leftInputFieldTextFontName: '',
        rightInputFieldTextFontName: '',
        detailsInputFieldTextFontName: '',
        leftInputFieldTextFontSize: '',
        rightInputFieldTextFontSize: '',
        detailsInputFieldTextFontSize: '',
      },
      inputFieldHeightAndWidth: {
        leftInputFieldHeight: '',
        leftInputFieldWidth: '',
        rightInputFieldHeight: '',
        rightInputFieldWidth: '',
        detailsInputFieldHeight: '',
        detailsInputFieldWidth: '',
      },
      inputFieldBorders: {
        leftInputFieldBorderBottomWidth: '',
        leftInputFieldBorderTopWidth: '',
        leftInputFieldBorderRightWidth: '',
        leftInputFieldBorderLeftWidth: '',
        leftInputFieldBorderBottomStyle: '',
        leftInputFieldBorderTopStyle: '',
        leftInputFieldBorderRightStyle: '',
        leftInputFieldBorderLeftStyle: '',
        leftInputFieldBorderBottomColor: '',
        leftInputFieldBorderTopColor: '',
        leftInputFieldBorderRightColor: '',
        leftInputFieldBorderLeftColor: '',
        rightInputFieldBorderBottomWidth: '',
        rightInputFieldBorderTopWidth: '',
        rightInputFieldBorderRightWidth: '',
        rightInputFieldBorderLeftWidth: '',
        rightInputFieldBorderBottomStyle: '',
        rightInputFieldBorderTopStyle: '',
        rightInputFieldBorderRightStyle: '',
        rightInputFieldBorderLeftStyle: '',
        rightInputFieldBorderBottomColor: '',
        rightInputFieldBorderTopColor: '',
        rightInputFieldBorderRightColor: '',
        rightInputFieldBorderLeftColor: '',
        detailsInputFieldBorderBottomWidth: '',
        detailsInputFieldBorderTopWidth: '',
        detailsInputFieldBorderRightWidth: '',
        detailsInputFieldBorderLeftWidth: '',
        detailsInputFieldBorderBottomStyle: '',
        detailsInputFieldBorderTopStyle: '',
        detailsInputFieldBorderRightStyle: '',
        detailsInputFieldBorderLeftStyle: '',
        detailsInputFieldBorderBottomColor: '',
        detailsInputFieldBorderTopColor: '',
        detailsInputFieldBorderRightColor: '',
        detailsInputFieldBorderLeftColor: '',
      },
      inputFieldIcons: {
        leftInputFieldIconSource: '',
        rightInputFieldIconSource: '',
        detailsInputFieldIconSource: '',
        leftInputFieldIconPosition: '',
        rightInputFieldIconPosition: '',
        detailsInputFieldIconPosition: '',
        leftInputFieldIconSize: '',
        rightInputFieldIconSize: '',
        detailsInputFieldIconSize: '',
      },
      inputFieldMarginsAndPadding: {
        leftInputFieldMarginTop: '',
        leftInputFieldMarginRight: '',
        leftInputFieldMarginBottom: '',
        leftInputFieldMarginLeft: '',
        rightInputFieldMarginTop: '',
        rightInputFieldMarginRight: '',
        rightInputFieldMarginBottom: '',
        rightInputFieldMarginLeft: '',
        detailsInputFieldMarginTop: '',
        detailsInputFieldMarginRight: '',
        detailsInputFieldMarginBottom: '',
        detailsInputFieldMarginLeft: '',
        leftInputFieldPaddingTop: '',
        leftInputFieldPaddingRight: '',
        leftInputFieldPaddingBottom: '',
        leftInputFieldPaddingLeft: '',
        rightInputFieldPaddingTop: '',
        rightInputFieldPaddingRight: '',
        rightInputFieldPaddingBottom: '',
        rightInputFieldPaddingLeft: '',
        detailsInputFieldPaddingTop: '',
        detailsInputFieldPaddingRight: '',
        detailsInputFieldPaddingBottom: '',
        detailsInputFieldPaddingLeft: '',
      },
    },
    buttons: {
      numberOfButtons: null,
      buttonsBackgroundColor: {
        leftmostButtonBackgroundColor: '',
        secondButtonFromLeftBackgroundColor: '',
        leftmostButtonBackgroundColorHover: '',
        secondButtonFromLeftBackgroundColorHover: '',
      },
      buttonsText: {
        leftmostButtonTextContent: '',
        secondButtonFromLeftTextContent: '',
        leftmostButtonTextColor: '',
        secondButtonFromLeftTextColor: '',
        leftmostButtonTextFontName: '',
        secondButtonFromLeftTextFontName: '',
        leftmostButtonTextFontSize: '',
        secondButtonFromLeftTextFontSize: '',
      },
      buttonsBorders: {
        leftmostButtonBorderBottomWidth: '',
        leftmostButtonBorderTopWidth: '',
        leftmostButtonBorderRightWidth: '',
        leftmostButtonBorderLeftWidth: '',
        leftmostButtonBorderBottomStyle: '',
        leftmostButtonBorderTopStyle: '',
        leftmostButtonBorderRightStyle: '',
        leftmostButtonBorderLeftStyle: '',
        leftmostButtonBorderBottomColor: '',
        leftmostButtonBorderTopColor: '',
        leftmostButtonBorderRightColor: '',
        leftmostButtonBorderLeftColor: '',
        secondButtonFromLeftBorderBottomWidth: '',
        secondButtonFromLeftBorderTopWidth: '',
        secondButtonFromLeftBorderRightWidth: '',
        secondButtonFromLeftBorderLeftWidth: '',
        secondButtonFromLeftBorderBottomStyle: '',
        secondButtonFromLeftBorderTopStyle: '',
        secondButtonFromLeftBorderRightStyle: '',
        secondButtonFromLeftBorderLeftStyle: '',
        secondButtonFromLeftBorderBottomColor: '',
        secondButtonFromLeftBorderTopColor: '',
        secondButtonFromLeftBorderRightColor: '',
        secondButtonFromLeftBorderLeftColor: '',
        leftmostButtonBorderRadius: '',
        secondButtonFromLeftBorderRadius: '',
      },
      buttonsHeightAndWidth: {
        leftmostButtonHeight: '',
        leftmostButtonWidth: '',
        secondButtonFromLeftHeight: '',
        secondButtonFromLeftWidth: '',
      },
      buttonsMarginsAndPadding: {
        leftmostButtonMarginTop: '',
        leftmostButtonMarginRight: '',
        leftmostButtonMarginBottom: '',
        leftmostButtonMarginLeft: '',
        secondButtonFromLeftMarginTop: '',
        secondButtonFromLeftMarginRight: '',
        secondButtonFromLeftMarginBottom: '',
        secondButtonFromLeftMarginLeft: '',
        leftmostButtonPaddingTop: '',
        leftmostButtonPaddingRight: '',
        leftmostButtonPaddingBottom: '',
        leftmostButtonPaddingLeft: '',
        secondButtonFromLeftPaddingTop: '',
        secondButtonFromLeftPaddingRight: '',
        secondButtonFromLeftPaddingBottom: '',
        secondButtonFromLeftPaddingLeft: '',
      },
      buttonsBellsAndWhistles: {
        leftmostButtonBoxShadow: '',
        secondButtonFromLeftBoxShadow: '',
      },
    },
    footer: {
      footerBackgroundColor: '',
      height: '',
      width: '',
      displayType: 'block',
      footerHideShowTextFont: '',
      footerBorders: {
        footerBorderBottomWidth: '',
        footerBorderTopWidth: '',
        footerBorderRightWidth: '',
        footerBorderLeftWidth: '',
        footerBorderBottomStyle: '',
        footerBorderTopStyle: '',
        footerBorderRightStyle: '',
        footerBorderLeftStyle: '',
        footerBorderBottomColor: '',
        footerBorderTopColor: '',
        footerBorderRightColor: '',
        footerBorderLeftColor: '',
      },
      elements: [
        {
          doesItExist: true,
          id: 0,
          type: 'textLink',
          textContent: 'Book Now',
          socialMediaType: '',
          linkTo: 'https://demo.fareharbor.com/embeds/book/' + shortname + '/items/',
          height: '',
          width: '',
          fontName: '',
          fontSize: '20px',
          fontWeight: 'bolder',
          marginTop: '',
          marginRight: '10%',
          marginBottom: '',
          marginLeft: '2%',
        },
        {
          doesItExist: true,
          id: 1,
          type: 'textLink',
          textContent: 'Contact Us',
          socialMediaType: '',
          linkTo: '',
          height: '',
          width: '',
          fontName: '',
          fontSize: '',
          fontWeight: '',
          marginTop: '',
          marginRight: '',
          marginBottom: '',
          marginLeft: '5%',
        },
        {
          doesItExist: true,
          id: 2,
          type: 'textLink',
          textContent: 'Feedback',
          socialMediaType: '',
          linkTo: '',
          height: '',
          width: '',
          fontName: '',
          fontSize: '',
          fontWeight: '',
          marginTop: '',
          marginRight: '',
          marginBottom: '',
          marginLeft: '3%',
        },
        {
          doesItExist: true,
          id: 3,
          type: 'textLink',
          textContent: 'Legal',
          socialMediaType: '',
          linkTo: '',
          height: '',
          width: '',
          fontName: '',
          fontSize: '',
          fontWeight: '',
          marginTop: '',
          marginRight: '',
          marginBottom: '',
          marginLeft: '3%',
        },
        {
          doesItExist: true,
          id: 4,
          type: 'textLink',
          textContent: 'Share:',
          socialMediaType: '',
          linkTo: '',
          height: '',
          width: '',
          fontName: '',
          fontSize: '',
          fontWeight: '',
          marginTop: '',
          marginRight: '',
          marginBottom: '',
          marginLeft: '15%',
        },
        {
          doesItExist: true,
          id: 5,
          type: 'socialMedia',
          textContent: '',
          socialMediaType: 'facebook',
          linkTo: '',
          height: '25px',
          width: '25px',
          fontName: '',
          fontSize: '',
          fontWeight: '',
          marginTop: '',
          marginRight: '',
          marginBottom: '',
          marginLeft: '3%',
        },
        {
          doesItExist: true,
          id: 6,
          type: 'socialMedia',
          textContent: '',
          socialMediaType: 'twitter',
          linkTo: '',
          height: '25px',
          width: '25px',
          fontName: '',
          fontSize: '',
          fontWeight: '',
          marginTop: '',
          marginRight: '',
          marginBottom: '',
          marginLeft: '3%',
        },
      ],
    },
  },
}
