var FHConfig = {
  toolType: 'SearchInput',
  shortname: 'bodyglove',
  text: {
    fontPrimary: '',
    headerText: 'Book Tickets Now',
    mainActionButton: 'Book Now',
    textAlign: '',
  },
  colors: {
    headerColor: 'green',
    mainButtonColor: '',
    mainButtonTextColor: '',
  },
  structure: { // consider adding the itemID so we can pass it to the api call
    cards: {
      numberOfCards: null,
      cardText: {
        topCard: 'Reserve Now',
        secondCardDown: '',
        thirdCardDown: '',
        bottomCard: '',
        //RW: we should change this to fourthCardDown to avoid confusion
      },
      marginsAndPadding: {
        global: {
          marginLeft: '',
          marginRight: '',
          marginTop: '',
          marginBottom: '',
          paddingLeft: '',
          paddingRight: '',
          paddingTop: '',
          paddingBottom: '',
        },
      },
    },
    inputFields: {
      numberOfInputFields: null,
      inputFieldText: {
        leftmostFieldText: '',
        secondFieldFromLeftText: '',
        thirdFieldFromLeftText: '',
      },
      inputFieldHeightAndWidth: {
        leftmostFieldHeight: '',
        leftmostFieldWidth: '',
        secondFieldFromLeftHeight: '',
        secondFieldFromLeftWidth: '',
        thirdFieldFromLeftHeight: '',
        thirdFieldFromLeftWidth: '',
      },
      inputFieldBorders: {
        leftmostFieldBorderBottomWidth: '20px',
        leftmostFieldBorderTopWidth: '20px',
        leftmostFieldBorderRightWidth: '20px',
        leftmostFieldBorderLeftWidth: '20px',
        leftmostFieldBorderBottomStyle: 'dotted',
        leftmostFieldBorderTopStyle: 'dotted',
        leftmostFieldBorderRightStyle: 'dotted',
        leftmostFieldBorderLeftStyle: 'dotted',
        leftmostFieldBorderBottomColor: 'red',
        leftmostFieldBorderTopColor: 'red',
        leftmostFieldBorderRightColor: 'red',
        leftmostFieldBorderLeftColor: 'red',
        secondFieldFromLeftBorderBottomWidth: '20px',
        secondFieldFromLeftBorderTopWidth: '20px',
        secondFieldFromLeftBorderRightWidth: '20px',
        secondFieldFromLeftBorderLeftWidth: '20px',
        secondFieldFromLeftBorderBottomStyle: 'dotted',
        secondFieldFromLeftBorderTopStyle: 'dotted',
        secondFieldFromLeftBorderRightStyle: 'dotted',
        secondFieldFromLeftBorderLeftStyle: 'dotted',
        secondFieldFromLeftBorderBottomColor: 'red',
        secondFieldFromLeftBorderTopColor: 'red',
        secondFieldFromLeftBorderRightColor: 'red',
        secondFieldFromLeftBorderLeftColor: 'red',
        thirdFieldFromLeftBorderBottomWidth: '',
        thirdFieldFromLeftBorderTopWidth: '',
        thirdFieldFromLeftBorderRightWidth: '',
        thirdFieldFromLeftBorderLeftWidth: '',
        thirdFieldFromLeftBorderBottomStyle: '',
        thirdFieldFromLeftBorderTopStyle: '',
        thirdFieldFromLeftBorderRightStyle: '',
        thirdFieldFromLeftBorderLeftStyle: '',
        thirdFieldFromLeftBorderBottomColor: '',
        thirdFieldFromLeftBorderTopColor: '',
        thirdFieldFromLeftBorderRightColor: '',
        thirdFieldFromLeftBorderLeftColor: '',
      },
      inputFieldIcons: {
        leftmostFieldIconSource: '',
        secondFieldFromLeftIconSource: '',
        thirdFieldFromLeftIconSource: '',
        leftmostFieldIconPosition: '',
        secondFieldFromLeftIconPosition: '',
        thirdFieldFromLeftIconPosition: '',
        leftmostFieldIconSize: '',
        secondFieldFromLeftIconSize: '',
        thirdFieldFromLeftIconSize: '',
      },
    },
  },
}
